repos:
-   repo: local
    hooks:
    -   id: sanity-check
        name: sanity-check
        entry: bash scripts/sanity_test.sh
        language: system
        pass_filenames: false
        verbose: true
