tag_on_github:
    image: python:3
    stage: publish
    before_script:
    script:
      - git config remote.github.url >/dev/null || git remote add github https://${GH_TOKEN}@github.com/infobyte/faraday.git
      - git tag v$IMAGE_TAG -m "$(cat CHANGELOG/$IMAGE_TAG/white.md)"
      - git push origin v$IMAGE_TAG
    rules:
      - if: '$CI_COMMIT_TAG =~ /^white-v[0-9.]+$/'
        when: on_success
